### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by oksana-miazina** [oksana-divkit/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by miazina** [comment]
Peter Garrett is a long-time advocate and campaigner on a range of local and global issues. A member of Midnight Oil, one of Australia’s most successful bands, he served as a cabinet minister in the Rudd/Gillard Labor governments from 2007-13.

**Comment by oksana-miazina** [comment]
Peter Garrett is a long-time advocate and campaigner on a range of local and global issues. A member of Midnight Oil, one of Australia’s most successful bands, he served as a cabinet minister in the Rudd/Gillard Labor governments from 2007-13.
