### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by oksana-miazina** [oksana-divkit/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by miazina** [comment]
### The Hon Peter Garrett AM

- https://petergarrett.com.au/
- https://www.facebook.com/petergarrettofficial
- https://twitter.com/pgarrett
- https://www.instagram.com/peterrgarrett/

**Comment by oksana-miazina** [comment]
### The Hon Peter Garrett AM

- https://petergarrett.com.au/
- https://www.facebook.com/petergarrettofficial
- https://twitter.com/pgarrett
- https://www.instagram.com/peterrgarrett/
