### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by oksana-miazina** [oksana-divkit/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by miazina** [comment]
**since 1977**
Midnight Oil – vocalist, songwriter

**1989 – 1996**
President Australian Conservation Foundation 

**1993 – 1995**
Board Member Greenpeace International 

**2004-2013**
Labor Member for Kingsford Smith 

**2007-2010**
Minister for Environment & Arts

**2010-2013**
Minister for School Education & Youth

**Comment by miazina** [comment]
### Childhood & Early Life
**16th of April, 1953**  was born in Sydney, Australia. 
**1970-1976** studied art at the Australian National University and law at the University of New South Wales.

### Musical career and activism
**1973** joined the Australia based rock band ‘Midnight Oil’, as its lead vocalist.
**1980s** the band were strongly identified with environmental and Aboriginal rights causes. They were particularly critical of the military and foreign policy of the United States.
**2000** at the closing ceremony of the 2000 Olympic Games in Sydney, the group performed before then-Prime Minister, John Howard, and a television audience of hundreds of millions, wearing black overalls bearing the word "sorry". This referred to the Howard Government's refusal to apologise to Aboriginal Australians for the former policy of removing Aboriginal children from their families.
**2004** the band performed two gigs to earn money to help the survivors of the ‘Asian tsunami’ disaster 
**2007** presented Crowded House at the Australian leg of Live Earth.
**2009** the band performed in a bid to raise funds for the Victorian Bushfire Appeal
**2016** announced his first solo album, A Version of Now

### Political career
**1984** the Nuclear Disarmament Party (NDP) invited him to stand for a New South Wales seat in the Australian Senate at the federal election.
**1989-1993** President of the Australian Conservation Foundation
**1993-1995** working with the non-governmental initiative ‘Greenpeace’
**1999-2004** President of the Australian Conservation Foundation
**2004** joined the Labor Party and represented the political outfit during the ‘2004 Federal Elections’.
**2004-2013** Labor Member for Kingsford Smith
**2005-2006** Shadow Parliamentary Secretary for Reconciliation and the Arts
**2006-2007** Shadow Minister for Climate Change, Environment and Heritage
**2006-2007** Shadow Minister for the Arts
**2007-2010** was appointed as the Minister of Environment, Heritage and the Arts, after the Kevin Rudd government came into power.
**2010-2013** was appointed as the Minister For School Education, Early Childhood and Youth.

### Awards & Achievements
**2000** was felicitated with the ‘Australian Humanitarian Foundation Award’
**2001** received an honorary Doctorate of Letters from the University of New South Wales
**2003** Appointed Member of the Order of Australia
**2009** The Government of France granted Garrett the honour of being the officer of the ‘Order of Arts and Letters’
**2010** The Singer was felicitated with a ‘Leaders for a Living Planet Award’, by the organization named ‘World Wide Fund For Nature’.

### Personal Life & Legacy
**1986**  got married to Doris Ricono
**2007** the artist Michael Mucci entered a portrait of Garrett in the Archibald Prize (`The power and the passion`)

### Publications
**1987** Political Blues, Hodder and Stoughton, Sydney
**2015** Big Blue Sky: A Memoir

**Comment by oksana-miazina** [comment]
### Childhood & Early Life
**16th of April, 1953**  was born in Sydney, Australia. 
**1970-1976** studied art at the Australian National University and law at the University of New South Wales.

### Musical career and activism
**1973** joined the Australia based rock band ‘Midnight Oil’, as its lead vocalist.
**1980s** the band were strongly identified with environmental and Aboriginal rights causes. They were particularly critical of the military and foreign policy of the United States.
**2000** at the closing ceremony of the 2000 Olympic Games in Sydney, the group performed before then-Prime Minister, John Howard, and a television audience of hundreds of millions, wearing black overalls bearing the word "sorry". This referred to the Howard Government's refusal to apologise to Aboriginal Australians for the former policy of removing Aboriginal children from their families.
**2004** the band performed two gigs to earn money to help the survivors of the ‘Asian tsunami’ disaster 
**2007** presented Crowded House at the Australian leg of Live Earth.
**2009** the band performed in a bid to raise funds for the Victorian Bushfire Appeal
**2016** announced his first solo album, A Version of Now
**2017** Midnight Oil embarked on The Great Circle World Tour – with most dates selling out within 24 hours, the band played across 14 countries.

### Political career
**1984** the Nuclear Disarmament Party (NDP) invited him to stand for a New South Wales seat in the Australian Senate at the federal election.
**1989-1993** President of the Australian Conservation Foundation
**1993-1995** working with the non-governmental initiative ‘Greenpeace’
**1999-2004** President of the Australian Conservation Foundation
**2004** joined the Labor Party and represented the political outfit during the ‘2004 Federal Elections’.
**2004-2013** Labor Member for Kingsford Smith
**2005-2006** Shadow Parliamentary Secretary for Reconciliation and the Arts
**2006-2007** Shadow Minister for Climate Change, Environment and Heritage
**2006-2007** Shadow Minister for the Arts
**2007-2010** was appointed as the Minister of Environment, Heritage and the Arts, after the Kevin Rudd government came into power.
**2010-2013** was appointed as the Minister For School Education, Early Childhood and Youth.

### Awards & Achievements
**2000** was felicitated with the ‘Australian Humanitarian Foundation Award’
**2001** received an honorary Doctorate of Letters from the University of New South Wales
**2003** Appointed Member of the Order of Australia
**2006** winner Free Your Mind Award during MTV Australia Video Music Awards
**2009** The Government of France granted Garrett the honour of being the officer of the ‘Order of Arts and Letters’
**2010** The Singer was felicitated with a ‘Leaders for a Living Planet Award’, by the organization named ‘World Wide Fund For Nature’.

### Personal Life & Legacy
**1986**  got married to Doris Ricono
**2007** the artist Michael Mucci entered a portrait of Garrett in the Archibald Prize (`The power and the passion`)

### Publications
**1987** Political Blues, Hodder and Stoughton, Sydney
**2015** Big Blue Sky: A Memoir
